# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'hatsune' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hatsune

    pod 'GMGridView'
    pod 'IQKeyboardManager'
    pod 'MJRefresh'
    pod 'ZBarSDK'
    pod 'YYText'
    pod 'GTSDK'



  

end
